<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
   content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Welcome!</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/milligram/1.4.1/milligram.css">
</head>
<body>
<h2>Добро пожаловать!</h2>
<a href="/audiences"> Ко всем зрителям</a>
<br>
<a href="/films">Ко всем фильмам</a>
<br>
<a href="/cinemaHalls">Ко всем залам</a>
<br>
</body>
</html>